name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    name: Build and Deploy real time flight 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
         context: .
         dockerfile: Dockerfile
         push: false
         tags: ${{secrets.DOCKERHUB_USERNAME}}/spark:latest


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
         context: .
         dockerfile: Dockerfile
         push: true
         tags: ${{secrets.DOCKERHUB_USERNAME}}/spark:latest
