name: Docker Image CI

on:
  push:
    branches:
       - main

jobs:

  build:

    name: Build and Deploy real time flight 
    runs-on: ubuntu-latest
    steps:
    -name: Checkout code
     uses: actions/checkout@v4

    -name: Build Docker Image
     uses: docker/build-push-action@v5
     with:
         context: .
         dockerfile: Dockerfile
         push: false
         tags: ${{secrets.DOCKER_USERNAME}}/spark:$(date +%s)


    -name: Login to Docker Hub
     uses: docker/login-action@v3
     with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


    -name: Push to Docker Hub
     uses: docker/build-push-action@v5
     with:
         context: .
         dockerfile: Dockerfile
         push: true
         tags: ${{secrets.DOCKER_USERNAME}}/spark:$(date +%s)